--- #YAML:1.0
name:                VCS-SCCS
version:             0.12
abstract:            OO Interface to SCCS files
license:             perl
author:              
    - H.Merijn Brand <h.m.brand@xs4all.nl>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    File::Spec:                    0
    POSIX:                         0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
