--- 
abstract: OO Interface to SCCS files
author: 
  - H.Merijn Brand <h.m.brand@xs4all.nl>
configure_requires: 
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: Author, CPAN::Meta::Converter version 2.130880
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: VCS-SCCS
provides: 
  VCS::SCCS: 
    file: SCCS.pm
    version: '0.21'
recommends: 
  perl: '5.018000'
requires: 
  Carp: 0
  File::Spec: 0
  POSIX: 0
  Test::Harness: 0
  Test::More: 0
  Test::NoWarnings: 0
  perl: '5.006'
resources: 
  license: http://dev.perl.org/licenses/
  repository: http://repo.or.cz/r/VCS-SCCS.git
version: '0.21'
