--- #YAML:1.0
name:                VCS-SCCS
version:             0.02
abstract:            OO Interface to SCCS files
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - H.Merijn Brand <h.m.brand@xs4all.nl>
